[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 %(ENV_SCREEN_WIDTH)sx%(ENV_SCREEN_HEIGHT)sx%(ENV_SCREEN_DEPTH)s -ac +extension GLX +render -noreset
autorestart=true
priority=100
stdout_logfile=/var/log/supervisor/xvfb-stdout.log
stderr_logfile=/var/log/supervisor/xvfb-stderr.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB

[program:fluxbox]
command=/usr/bin/fluxbox
environment=DISPLAY=":99"
autorestart=true
priority=200
stdout_logfile=/var/log/supervisor/fluxbox-stdout.log
stderr_logfile=/var/log/supervisor/fluxbox-stderr.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -forever -nopw -shared -rfbport 5900 -xkb
autorestart=true
priority=300
stdout_logfile=/var/log/supervisor/x11vnc-stdout.log
stderr_logfile=/var/log/supervisor/x11vnc-stderr.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 6080
autorestart=true
priority=400
stdout_logfile=/var/log/supervisor/novnc-stdout.log
stderr_logfile=/var/log/supervisor/novnc-stderr.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
